version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: caballeros_db
    environment:
      POSTGRES_USER: ${DB_USER}      # <--- Lee del .env
      POSTGRES_PASSWORD: ${DB_PASSWORD} # <--- Lee del .env
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"            # <--- Lee del .env (5433)
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: